export const tarotDict = {
  '-1': 'Reverie',
  '0': 'The Fool',
  '1': 'The Magician',
  '2': 'The High Priestess',
  '3': 'The Empress',
  '4': 'The Emperor',
  '5': 'The Hierophant',
  '6': 'The Lover',
  '7': 'The Chariot',
  '8': 'Strength',
  '9': 'The Hermit',
  '10': 'Wheel of Fortune',
  '11': 'Justice',
  '12': 'The Hanged Man',
  '13': 'Death',
  '14': 'Temperance',
  '15': 'The Devil',
  '16': 'The Tower',
  '17': 'The Star',
  '18': 'The Moon',
  '19': 'The Sun',
  '20': 'Judgement',
  '21': 'The World',
  '22': 'Ace of Wands',
  '23': 'Two of Wands',
  '24': 'Three of Wands',
  '25': 'Four of Wands',
  '26': 'Five of Wands',
  '27': 'Six of Wands',
  '28': 'Seven of Wands',
  '29': 'Eight of Wands',
  '30': 'Nine of Wands',
  '31': 'Ten of Wands',
  '32': 'Page of Wands',
  '33': 'Knight of Wands',
  '34': 'Queen of Wands',
  '35': 'King of Wands',
  '36': 'Ace of Chalices'
};